apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: REPO
    description: Repository name
    value: nr-nmp
  - name: COMPONENT
    description: Component name
    value: frontend
  - name: ORG
    description: Organization name; e.g. bcgov or bcdevops
    value: bcgov
  - name: TAG
    description: Image tag; e.g. PR number or latest
    required: true
  - name: TARGET
    description: Deployment target; e.g. PR number, test or prod
    required: true
  - name: SSOAUTH
    description: SSO Auth Server URL
    required: true
  - name: CPU_REQUEST
    value: 50m
  - name: MEMORY_REQUEST
    value: 175Mi
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      type: ClusterIP
      ports:
        - port: 3005
          targetPort: 3000
          protocol: TCP
          name: http-3000
      selector:
        service: ${REPO}-${TARGET}-${COMPONENT}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
        deployment: ${REPO}-${TARGET}-${COMPONENT}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: ${REPO}-${TARGET}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${REPO}-${TARGET}
            deployment: ${REPO}-${TARGET}-${COMPONENT}
            service: ${REPO}-${TARGET}-${COMPONENT}
        spec:
          containers:
            - name: ${REPO}-${TARGET}-${COMPONENT}
              image: ghcr.io/${ORG}/${REPO}/${COMPONENT}:${TAG}
              # TODO: be more specific when giving permissions
              securityContext:
                capabilities:
                  add: ["NET_BIND_SERVICE"]
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: VITE_BACKEND_URL
                  value: https://${REPO}-${TARGET}-backend.apps.silver.devops.gov.bc.ca
                - name: BACKEND_URL
                  value: https://${REPO}-${TARGET}-backend.apps.silver.devops.gov.bc.ca
                - name: VITE_PORT
                  value: '5173'
                - name: SSO_AUTH_SERVER_URL
                  value: ${SSOAUTH}
                - name: SSO_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-keycloak
                      key: SSO_CLIENT_ID
                - name: SSO_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: ${REPO}-keycloak
                      key: SSO_CLIENT_SECRET

              ports:
                - name: container-port
                  containerPort: 5173
              readinessProbe:
                httpGet:
                  port: container-port
              livenessProbe:
                httpGet:
                  port: container-port
              startupProbe:
                tcpSocket:
                  port: container-port
                failureThreshold: 5
                initialDelaySeconds: 90
                periodSeconds: 15
                timeoutSeconds: 10
                failureThreshold: 30
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${REPO}-${TARGET}
      name: ${REPO}-${TARGET}-${COMPONENT}
    spec:
      host: ${REPO}-${TARGET}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: http-3000
      to:
        kind: Service
        name: ${REPO}-${TARGET}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
