apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: APP
    description: Application name
    value: nr-nmp
  - name: COMPONENT
    description: Component name
    value: backend
  - name: ORG
    description: Organization name; e.g. bcgov or bcdevops
    value: bcgov
  - name: IMAGE_TAG
    description: Image tag; e.g. PR number or latest
    required: true
  - name: TARGET
    description: Deployment target; e.g. PR number, test or prod
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user.
    from: '[a-zA-Z0-9]{16}'
    generate: expression
  - name: NAME_SUFFIX
    description: Suffix for the name
    required: true
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: nr-nmp${NAME_SUFFIX}
      name: nr-nmp-backend${NAME_SUFFIX}
    spec:
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 3000
          protocol: TCP
          name: http-3000
      selector:
        service: nr-nmp-backend${NAME_SUFFIX}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: nr-nmp${NAME_SUFFIX}
        deployment: nr-nmp-backend${NAME_SUFFIX}
      name: nr-nmp-backend${NAME_SUFFIX}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: nr-nmp-backend${NAME_SUFFIX}
      template:
        metadata:
          labels:
            app: nr-nmp${NAME_SUFFIX}
            deployment: nr-nmp-backend${NAME_SUFFIX}
            service: nr-nmp-backend${NAME_SUFFIX}
        spec:
          containers:
            - name: nr-nmp-backend${NAME_SUFFIX}
              image: ghcr.io/bcgov/nr-nmp/backend:${IMAGE_TAG}
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: POSTGRES_HOST
                  value: nr-nmp-database${NAME_SUFFIX}
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: nr-nmp-database${NAME_SUFFIX}
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nr-nmp-database${NAME_SUFFIX}
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: nr-nmp-database${NAME_SUFFIX}
                      key: database-user
              ports:
                - containerPort: 3000
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /api/health
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 90
                periodSeconds: 15
                timeoutSeconds: 10
                successThreshold: 3
                failureThreshold: 30
              livenessProbe:
                successThreshold: 1
                failureThreshold: 5
                httpGet:
                  path: /api/health
                  port: 3000
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 30
                timeoutSeconds: 5
              resources: # this is optional
                limits:
                  cpu: 150m
                  memory: 150Mi
                requests:
                  cpu: 50m
                  memory: 75Mi
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: nr-nmp${NAME_SUFFIX}
      name: nr-nmp-backend${NAME_SUFFIX}
    spec:
      host: nr-nmp-backend${NAME_SUFFIX}.apps.silver.devops.gov.bc.ca
      port:
        targetPort: http-3000
      to:
        kind: Service
        name: nr-nmp-backend${NAME_SUFFIX}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
