apiVersion: v1
kind: Template
parameters:
  - name: NAME_SUFFIX
    required: true
  - name: DB_PASSWORD
    required: true
  - name: DB_USER
    required: true
  - name: DB_NAME
    required: true
  - name: DB_PORT
    required: true
object:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APP}-${TARGET}-${COMPONENT}
      labels:
        app: ${APP}-${TARGET}
    stringData:
      database-name: ${DB_NAME}
      database-password: ${DB_PASSWORD}
      database-port: ${DB_PORT}
      database-user: ${DB_USER}
