apiVersion: v1
kind: Template
parameters:
  - name: NAME_SUFFIX
    required: true
object:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${APP}-${TARGET}-${COMPONENT}
      labels:
        app: ${APP}-${TARGET}
    stringData:
      database-name: postgres
      database-password: ${DB_PASSWORD}
      database-port: "5432"
      database-user: postgres