apiVersion: v1
kind: Template
parameters:
  - name: NAME_SUFFIX
    required: true
  - name: DB_PASSWORD
    required: true
  - name: DB_USER
    required: true
  - name: DB_NAME
    required: true
  - name: DB_PORT
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: nr-nmp-pg12${NAME_SUFFIX}
    stringData:
      database-name: ${DB_NAME}
      database-password: ${DB_PASSWORD}
      database-port: ${DB_PORT}
      database-user: ${DB_USER}
