apiVersion: v1
kind: Template
parameters:
  - name: TARGET
    required: true
  - name: ENV
    required: true
  - name: DB_PASSWORD
    required: true
  - name: DB_USER
    required: true
  - name: DB_NAME
    required: true
  - name: DB_PORT
    required: true
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: nr-nmp-database-${TARGET}
    stringData:
      database-name: ${DB_NAME}
      database-password: ${DB_PASSWORD}
      database-port: ${DB_PORT}
      database-user: ${DB_USER}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-openshift-ingress
      labels:
        template: openshift-test
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: ingress
      policyTypes:
        - Ingress
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-same-namespace
      labels:
        template: nr-spar-backend-network-security-policy
    spec:
      podSelector: {}
      ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                environment: dev
                name: fa23a0
      policyTypes:
        - Ingress