name: .Deploys

on:
  workflow_call:
    inputs:
      environment:
        description: GitHub environment; e.g. PR number (omit), TEST or PROD
        required: false
        type: string
      tag: 
        description: Image tag; e.g. PR number or latest
        default: ${{ github.event.number }}
        required: false
        type: string
      target:
        description: Deployment target; e.g. PR number (omit), test or prod
        default: ${{ github.event.number }}
        required: false
        type: string

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: bcgov-nr/action-deployer-openshift@v3.0.1
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          oc_version: "4.14.37"
          file: common/openshift.init.yml
          overwrite: true
          parameters:
            -p NAME_SUFFIX=${{ inputs.target }}
            -p DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            -p DB_USER=${{ secrets.DB_USER }}
            -p DB_NAME=${{ secrets.DB_NAME }}
            -p DB_PORT=${{ secrets.DB_PORT }}
  
  database:
    name: Database
    needs: [init]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy Database
        uses: bcgov-nr/action-deployer-openshift@v3.0.1
        with:
          oc_namespace: ${{ vars.OC_NAMESPACE }}
          oc_server: ${{ vars.OC_SERVER }}
          oc_token: ${{ secrets.OC_TOKEN }}
          file: database/openshift.deploy.yml
          overwrite: false
          parameters:
            -p TAG=${{ inputs.tag }} 
            -p TARGET=${{ inputs.target }}

  # backend:
  #   name: Backend
  #   needs: [database]
  #   environment: ${{ inputs.environment }}
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Deploy Backend
  #       uses: bcgov-nr/action-deployer-openshift@v3.0.1
  #       with:
  #         oc_namespace: ${{ vars.OC_NAMESPACE }}
  #         oc_server: ${{ vars.OC_SERVER }}
  #         oc_token: ${{ secrets.OC_TOKEN }}
  #         file: backend/openshift.deploy.yml
  #         overwrite: true
  #         parameters:
  #           -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}
  #         verification_path: /api/health
  #         verification_retry_attempts: "5"
  #         verification_retry_seconds: "15"

  # frontend:
  #   name: Frontend
  #   # needs: [backend]
  #   environment: ${{ inputs.environment }}
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - name: Deploy Frontend
  #       uses: bcgov-nr/action-deployer-openshift@v3.0.1
  #       with:
  #         oc_namespace: ${{ vars.OC_NAMESPACE }}
  #         oc_server: ${{ vars.OC_SERVER }}
  #         oc_token: ${{ secrets.OC_TOKEN }}
  #         file: frontend/openshift.deploy.yml
  #         overwrite: true
  #         parameters:
  #           -p TAG=${{ inputs.tag }} -p TARGET=${{ inputs.target }}
